[package]
name = "aoc-2018-rs"
version = "0.1.0"
authors = ["Greg Manning <greg@gregmanning.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-runner = "0.2.2"
aoc-runner-derive="0.2.2"
